OEL-2794: Update components to run on Drupal 10.2.x
openeuropa/oe_subscriptions pull request #20
Opened 2024-01-19 14:37 UTC by AaronGilMartinez

2024-01-22 14:09 UTC, brummbar requested changes

2024-01-22 14:09 UTC, brummbar commented on composer.json
> +        "drupal/core": "^10.1 || ^10.2",
Let's just put ^10 here, without further restrictions.

2024-01-22 14:09 UTC, brummbar commented on composer.json
> +        "drupal/core-composer-scaffold": "^10.1 || ^10.2",
Same here.

2024-01-22 16:43 UTC, AaronGilMartinez commented on composer.json
> +        "drupal/core": "^10.1 || ^10.2",
Done

2024-01-22 16:43 UTC, AaronGilMartinez commented on composer.json
> +        "drupal/core-composer-scaffold": "^10.1 || ^10.2",
Done

2024-01-23 15:27 UTC, brummbar approved these changes

2024-01-23 15:27 UTC, merged