OEL-2674: Implement email validation for the subscription link - WIP
openeuropa/oe_subscriptions pull request #4
Opened 2023-11-22 15:53 UTC by AaronGilMartinez

2023-11-28 13:45 UTC, brummbar requested changes
Let's start with these changes.

2023-11-28 13:45 UTC, brummbar commented on modules/oe_subscriptions_anonymous/oe_subscriptions_anonymous.install
> +        'length' => 255,
Let's use the same value as \Drupal\Core\Field\Plugin\Field\FieldType\EmailItem::schema .

2023-11-28 13:45 UTC, brummbar commented on modules/oe_subscriptions_anonymous/oe_subscriptions_anonymous.install
> +        'default' => '',
Is there a reason for empty string as default?

2023-11-28 13:45 UTC, brummbar commented on modules/oe_subscriptions_anonymous/oe_subscriptions_anonymous.install
> +        'length' => 255,
Int is the correct type.

2023-11-28 13:45 UTC, brummbar commented on modules/oe_subscriptions_anonymous/oe_subscriptions_anonymous.routing.yml
> +  path: '/confirm/{flag}/{entity_id}/{email}/{hash}'
These routes are too generic, we might clash with other modules. We need to pick a starting point for these.
Let's have them start with /subscribe/, so /subscribe/confirm, subscribe/cancel, subscribe/request

2023-11-28 13:45 UTC, brummbar commented on modules/oe_subscriptions_anonymous/src/AnonymousSubscriptionManager.php
> +    if (!$this->mailValidatorService->isValid($mail)) {
It's not the job of this service to validate the email.

2023-11-28 13:45 UTC, brummbar commented on modules/oe_subscriptions_anonymous/src/AnonymousSubscriptionManager.php
> +class AnonymousSubscriptionManager implements AnonymousSubscriptionManagerInterface {
This needs to be split in two services.
One service will handle tokens. We will need this later also for allowing anon users to access their subscriptions page. It should have methods like:

1. `isValid(string $token, string $email, string $scope)`: checks if a token exists and is valid (not expired).
2. `get(string $email, string $scope)`: returns a token. It will create the entry if needed, or updated it.
3. `delete(string $email, string $scope)`: deletes a token given some parameters.
4. `deleteExpired()`: deletes all expired tokens.

For `$scope` above, we need to choose what to do:
- we have a single service for the subscription process and the subscriptions edit page. In this case, we build the scope using a static method in an helper class.
- we have a service per token type, but we need to have double interfaces and all.

2023-11-28 13:45 UTC, brummbar commented on modules/oe_subscriptions_anonymous/src/AnonymousSubscriptionManager.php
> +      $account = User::load($user);
Always use dependency injection.

2023-11-28 13:45 UTC, brummbar commented on modules/oe_subscriptions_anonymous/src/AnonymousSubscriptionManager.php
> +class AnonymousSubscriptionManager implements AnonymousSubscriptionManagerInterface {
The other service will be the AnonymousSubscriptionManager, which should just take care of subscribing anonymous users. The method for now should be just `subscribe(string $email, FlagInterface $flag, string $entity_id)`.
The validation of the hash is to be done in the controller (like core does).

2023-11-29 07:59 UTC, AaronGilMartinez commented on modules/oe_subscriptions_anonymous/oe_subscriptions_anonymous.install
> +        'length' => 255,
Added

2023-11-29 08:01 UTC, AaronGilMartinez commented on modules/oe_subscriptions_anonymous/oe_subscriptions_anonymous.install
> +        'default' => '',
Removed

2023-11-29 08:06 UTC, AaronGilMartinez commented on modules/oe_subscriptions_anonymous/oe_subscriptions_anonymous.install
> +        'length' => 255,
Changed

2023-11-29 08:11 UTC, AaronGilMartinez commented on modules/oe_subscriptions_anonymous/oe_subscriptions_anonymous.routing.yml
> +  path: '/confirm/{flag}/{entity_id}/{email}/{hash}'
Added

2023-11-29 08:20 UTC, AaronGilMartinez commented on modules/oe_subscriptions_anonymous/src/AnonymousSubscriptionManager.php
> +    if (!$this->mailValidatorService->isValid($mail)) {
Removed

2023-11-29 08:45 UTC, AaronGilMartinez commented on modules/oe_subscriptions_anonymous/src/AnonymousSubscriptionManager.php
> +      $account = User::load($user);
Done

2023-11-30 08:07 UTC, AaronGilMartinez commented on modules/oe_subscriptions_anonymous/src/AnonymousSubscriptionManager.php
> +class AnonymousSubscriptionManager implements AnonymousSubscriptionManagerInterface {
Service splitted, using a single service for the scope.

2023-12-06 14:08 UTC, merged